project:
  type: website

website:
  title: "Welcome"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css
    highlight-style: eiffel

editor: visual

